function z_dot = DroneDynamics(pn,pe,pd,u,v,w,p,q,r,phi,theta,psi,nFR,nFL,nRR,nRL)
%DroneDynamics
%    Z_DOT = DroneDynamics(PN,PE,PD,U,V,W,P,Q,R,PHI,THETA,PSI,nFR,nFL,nRR,nRL)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Nov-2023 20:51:45

t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = nFL.^2;
t10 = nFR.^2;
t11 = nRL.^2;
t12 = nRR.^2;
t13 = 1.0./t4;
t14 = t9.*1.248554292436122e-3;
t15 = t10.*1.248554292436122e-3;
t16 = t11.*1.248554292436122e-3;
t17 = t12.*-1.248554292436122e-3;
mt1 = [-t7.*w+t3.*t4.*u+t4.*t6.*v;-u.*(t2.*t6+t3.*t5.*t7)+v.*(t2.*t3-t5.*t6.*t7)-t4.*t5.*w;u.*(t5.*t6+t2.*t3.*t7)-v.*(t3.*t5-t2.*t6.*t7)+t2.*t4.*w;-q.*w+r.*v+t5.*t6.*(9.81e+2./1.0e+2)+t2.*t3.*t7.*(9.81e+2./1.0e+2);p.*w-r.*u-t3.*t5.*(9.81e+2./1.0e+2)+t2.*t6.*t7.*(9.81e+2./1.0e+2)];
mt2 = [t9.*2.069765738766338e-5+t10.*2.069765738766338e-5+t11.*2.069765738766338e-5+t12.*2.069765738766338e-5-p.*v+q.*u+t2.*t4.*(9.81e+2./1.0e+2)];
mt3 = [t14-t15+t16+t17-q.*r.*8.700255003477322e-1;t14+t15-t16+t17+p.*r.*8.700255003477322e-1;t9.*-8.296327210539277+t10.*8.296327210539277+t11.*8.296327210539277-t12.*8.296327210539277;p+q.*t5.*t8+r.*t2.*t8;q.*t2-r.*t5;q.*t5.*t13+r.*t2.*t13];
z_dot = [mt1;mt2;mt3];
end
