function f = DroneSimulation(pn,pe,pd,u,v,w,phi,theta,psi,p,q,r,Z_T_c,L_T_c,M_T_c,N_T_c)
%DroneSimulation
%    F = DroneSimulation(PN,PE,PD,U,V,W,PHI,THETA,PSI,P,Q,R,Z_T_c,L_T_c,M_T_c,N_T_c)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Nov-2023 16:46:41

t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = q.*w;
t10 = r.*v;
t11 = 1.0./t4;
t12 = -t10;
t13 = t5.*t6.*(9.81e+2./1.0e+2);
t14 = t2.*t3.*t7.*(9.81e+2./1.0e+2);
t15 = t9+t12+t13+t14;
et1 = L_T_c.*5.660622590765625e-8;
et2 = M_T_c.*5.660622590765626e-8;
et3 = N_T_c.*(-5.660622590765629e-8);
et4 = Z_T_c.*(-5.660622590765625e-8);
et5 = L_T_c.*(-5.660622590765624e-8);
et6 = M_T_c.*5.660622590765626e-8;
et7 = N_T_c.*5.660622590765625e-8;
et8 = Z_T_c.*(-5.660622590765625e-8);
mt1 = [-t7.*w+t3.*t4.*u+t4.*t6.*v;-u.*(t2.*t6+t3.*t5.*t7)+v.*(t2.*t3-t5.*t6.*t7)-t4.*t5.*w;u.*(t5.*t6+t2.*t3.*t7)-v.*(t3.*t5-t2.*t6.*t7)+t2.*t4.*w;t15;t15];
mt2 = [L_T_c.*(-2.070303046875e-5)-M_T_c.*2.070303046875e-5-N_T_c.*2.070303046875e-5-Z_T_c.*2.070303046875e-5+t15;-p.*w+r.*u-t3.*t5.*(9.81e+2./1.0e+2)+t2.*t6.*t7.*(9.81e+2./1.0e+2);p.*v-q.*u+t2.*t4.*(9.81e+2./1.0e+2)];
mt3 = [q.*r.*(-1.78485830775e-9)+sqrt(abs(et1+et2+et3+et4)).*4.52935e-5;p.*r.*1.78485830775e-9+sqrt(abs(et5+et6+et7+et8)).*4.52935e-5];
mt4 = [sqrt(abs(L_T_c.*7.119747363223659e-5-M_T_c.*7.119747363223659e-5+N_T_c.*7.119747363223659e-5-Z_T_c.*7.119747363223659e-5)).*8.47e-5;p+q.*t5.*t8+r.*t2.*t8;q.*t2-r.*t5;q.*t5.*t11+r.*t2.*t11];
f = [mt1;mt2;mt3;mt4];
end
